name: "[Workflow] Pull Request"

on:
  workflow_call:
    inputs:
        build_latest:
            description: 'Branch name'
            type: boolean
            default: false
        semver_tag:
            description: 'Semver tag'
            required: true
            type: string

permissions:
  id-token: write
  contents: write
  security-events: write
  pull-requests: write
  actions: none
  checks: none
  deployments: none
  issues: write
  packages: none
  repository-projects: none
  statuses: none

defaults:
  run:
    shell: bash

jobs:
  build_scan_push:
    name: "Docker build, Snyk scan, ECR push"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        data:
          - docker_build_directory: .
            image_app_name: mock-onelogin
            ecr_repository: mock-onelogin

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: '^1.22'
          cache-dependency-path: "**/*.sum"

      - name: Run tests
        run: |
          go test -v ./...

      - uses: unfor19/install-aws-cli-action@f5b46b7f32cf5e7ebd652656c5036bf83dd1e60c # 1.0.8

      - name: Configure OIDC AWS credentials for ECR push and pull
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          role-to-assume: ${{ vars.OIDC_ECR_ROLE }}
          role-session-name: opg-mock-onelogin-github-actions-ecr-push-pull
          role-duration-seconds: 900
          aws-region: eu-west-1

      - name: Set up Docker
        uses: docker/setup-docker-action@1a6edb0ba9ac496f6850236981f15d8f9a82254d # v5.0.0
        with:
          daemon-config: |
            {
              "debug": false,
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: ECR Login
        id: login_ecr
        uses: aws-actions/amazon-ecr-login@c962da2960ed15f492addc26fffa274485265950 # v2.0.2
        with:
          registries: 311462405659

      - name: Generate tags for Docker
        env:
          SEMVER_TAG: ${{ inputs.semver_tag }}
          ECR_REGISTRY: ${{ steps.login_ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ matrix.data.ecr_repository }}
        id: docker_tags
        run: |
          if ${{ inputs.build_latest }}; then
            echo "tags=$ECR_REGISTRY/$ECR_REPOSITORY:latest,$ECR_REGISTRY/$ECR_REPOSITORY:$SEMVER_TAG,$ECR_REGISTRY/$ECR_REPOSITORY:main-$SEMVER_TAG" >> $GITHUB_OUTPUT
          else
            echo "tags=$ECR_REGISTRY/$ECR_REPOSITORY:$SEMVER_TAG" >> $GITHUB_OUTPUT
          fi
          echo "semver_tag=$ECR_REGISTRY/$ECR_REPOSITORY:$SEMVER_TAG" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Build and push
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
        with:
          context: .
          file: ${{ matrix.data.docker_build_directory }}/Dockerfile
          load: true
          tags: ${{ steps.docker_tags.outputs.tags }}

      - name: Snyk Scan
        uses: ministryofjustice/opg-github-actions/actions/snyk-scan@2186f4ee10b7f2839e0c795dcd01c729e6d1d4c0 # v4.8.1
        with:
          SNYK_TEST_IMAGE: ${{ steps.docker_tags.outputs.semver_tag }}
          SNYK_TOKEN: ${{ secrets.SNYK_OPG_ORG_TOKEN }}
          snyk_test_args: --serverity-threshold=high

      - name: Upload Snyk scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@0d579ffd059c29b07949a3cce3983f0780820c98 # v4.32.6
        if: always()
        with:
          sarif_file: test-results/snyk.sarif
          category: snyk-docker

      - name: Push to ECR
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ${{ matrix.data.docker_build_directory }}/Dockerfile
          push: true
          tags: ${{ steps.docker_tags.outputs.tags }}
