name: "[Workflow] Path to Live"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  security-events: write
  pull-requests: write
  actions: none
  checks: none
  deployments: none
  issues: write
  packages: none
  repository-projects: none
  statuses: none

defaults:
  run:
    shell: bash

jobs:
  branch_name:
    name: "Generate a safe branch name"
    uses: ministryofjustice/opg-github-workflows/.github/workflows/data-parse-branch-name.yml@main

  semver_tag:
    needs: [branch_name]
    name: "Generate the semver tag value"
    uses: ministryofjustice/opg-github-workflows/.github/workflows/data-parse-semver-tag.yml@main
    with:
      branch_name: "${{ needs.branch_name.outputs.parsed }}"
    secrets: inherit

  build_scan_push:
    needs: [branch_name, semver_tag]
    name: "Build, scan and push the image"
    uses: ./.github/workflows/_docker_build_scan_push.yml
    with:
      build_latest: true
      semver_tag: "${{ needs.semver_tag.outputs.tag }}"
    secrets: inherit

  end:
    name: 'End of workflow'
    runs-on: 'ubuntu-latest'
    needs: [branch_name, semver_tag, build_scan_push]
    steps:
      - name: "Output data"
        run: |
          echo "== BRANCH =="
          echo "Raw: ${{ needs.branch_name.outputs.raw }}"
          echo "Parsed: ${{ needs.branch_name.outputs.parsed }}"
          echo "Alphanumeric: ${{ needs.branch_name.outputs.alphanumeric }}"
          echo "== SEMVER =="
          echo "Tag: ${{ needs.semver_tag.outputs.tag }}"
